repos:
    - repo: local
      hooks:
          - id: kics-scan-local
            name: Kics scan
            language: docker_image
            entry: checkmarx/kics scan -p /src --no-progress --cloud-provider gcp --disable-secrets
            verbose: true
