name: Test KICS action PR comment

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run kics Scan
      uses: cx-andre-peixoto/kics-github-action@v2.1.9
      with:
        path: ec2
        token: ${{ secrets.GITHUB_TOKEN }}
        output_path: results-dir/
        output_formats: 'json,sarif'
        ignore_on_exit: results
        enable_comments: true
    - name: Show results
      run: |
        cat results-dir/results.sarif
        cat results-dir/results.json
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results-dir/results.sarif
