name: Test KICS action PR comment

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run kics Scan
      uses: cx-artur-ribeiro/kics-github-action@v2.1.9
      with:
        path: test/samples/positive1.tf,test/samples/positive2.tf
        token: ${{ secrets.GITHUB_TOKEN }}
        output_path: myResults/
        output_formats: 'json,sarif'
        ignore_on_exit: results
        enable_comments: true
    - name: Show results
      run: |
        cat myResults/results.sarif
        cat myResults/results.json
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: myResults/results.sarif
